/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cloud_logic_custom": [
        {
            "name": "api296dcdab",
            "endpoint": "https://o2l8wrh4qd.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-2:7a9c80df-626e-4f0a-b684-8df44eba502c",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_fQCxBW8e6",
    "aws_user_pools_web_client_id": "1nl6rt8jatt1ef2k040vstugbf",
    "oauth": {}
};


export default awsmobile;
